package uk.gov.hmcts.reform.finrem.ccd.domain;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public enum MiamDomesticViolence {
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_1,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_2,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_3,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_4,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_5,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_6,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_7,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_8,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_9,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_10,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_11,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_12,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_13,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_14,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_15,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_16,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_17,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_18,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_19,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_20,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_21,
    FR_MS_MIAM_DOMESTIC_VIOLENCE_CHECKLIST_VALUE_22
}
