package uk.gov.hmcts.reform.finrem.ccd.domain;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public enum PotentialAllegation {
    POTENTIAL_ALLEGATION_CHECKLIST_1,
    POTENTIAL_ALLEGATION_CHECKLIST_2,
    POTENTIAL_ALLEGATION_CHECKLIST_3,
    POTENTIAL_ALLEGATION_CHECKLIST_4,
    POTENTIAL_ALLEGATION_CHECKLIST_5,
    POTENTIAL_ALLEGATION_CHECKLIST_6,
    POTENTIAL_ALLEGATION_CHECKLIST_7,
    POTENTIAL_ALLEGATION_CHECKLIST_8,
    POTENTIAL_ALLEGATION_CHECKLIST_9,
    POTENTIAL_ALLEGATION_CHECKLIST_10,
    POTENTIAL_ALLEGATION_CHECKLIST_12,
    POTENTIAL_ALLEGATION_CHECKLIST_13,
    POTENTIAL_ALLEGATION_CHECKLIST_14,
    NOT_APPLICABLE
}
